columns = [
"age",
"class of worker",
"industry code",
"occupation code",
"education",
"adjusted gross income",
"wage per hour",
"marital status",
"major industry code",
"major occupation code",
"race",
"enrolled in edu inst last wk",
"sex",
"hispanic Origin",
"member of a labor union",
"reason for unemployment",
"full or part time employment stat",
"capital gains",
"capital losses",
"tax filer status",
"divdends from stocks",
"region of previous residence",
"state of previous residence",
"detailed household and family stat",
"detailed household summary in househo",
"instance weight",
"migration code-change in msa",
"migration code-change in reg",
"migration code-move within reg",
"live in this house 1 year ago",
"migration prev res in sunbelt",
"num persons worked for employer",
"family members under 18",
"country of birth father",
"country of birth mother",
"country of birth self",
"citizenship",
"own business or self employed",
"fill inc questionnaire for veteran's admin",
"veterans benefits",
"weeks worked in year",
"income"
]